# .github/workflows/test.yml

name: Test con docker run de Odoo CE

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar y ejecutar manifestoo
        id: manifestoo
        run: |
          pip install manifestoo-core
          MODS=$(python -m manifestoo_core -d repos list --installable)
          MOD_LIST=$(echo "$MODS" | tr '
' ',' | sed 's/,$//')
          echo "modules=$MOD_LIST" >> $GITHUB_OUTPUT
