# .github/workflows/test.yml

name: Test con imagen Odoo CE

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/victorm-ditay/odoo-ce:18.0
      
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar manifestoo
        run: pip install manifestoo-core

      - name: Detectar módulos instalables
        id: manifestoo
        run: |
          MODS=$(manifestoo -d repos list --installable)
          echo "modules=$(echo $MODS | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT

      - name: Ejecutar tests con Odoo
        run: |
          odoo \
            --addons-path=/usr/lib/python3/dist-packages/odoo/addons,repos \
            --db_host=localhost --db_user=odoo --db_password=odoo \
            --test-enable --stop-after-init \
            --modules=${{ steps.manifestoo.outputs.modules }}
